from setuptools import setup, find_packages

setup(
    name='GASP',
    version='1.0.1',
    packages=find_packages(),
    include_package_data=True,
    url='software.knowledge-technology.info#gasp',
    license='MIT License',
    author='Fares Abawi',
    author_email='fares.abawi@uni-hamburg.de',
    maintainer='Fares Abawi',
    maintainer_email='fares.abawi@uni-hamburg.de',
    description='Social cue integration for dynamic saliency prediction',
    install_requires=['cython==3.0.0a9',
                      'pandas==1.3.2',
                      # 'opencv-python==4.2.0.34',
                      'scikit-build==0.12.0',
                      'opencv-contrib-python==4.5.3.56',
                      'matplotlib==3.4.3',
                      'seaborn==0.11.2',
                      'torch==1.7.1',
                      'tqdm==4.62.1',
                      'librosa==0.8.1',
                      'cffi==1.14.6',
                      'resampy==0.2.2',
                      'sounddevice==0.4.2',
                      'torchvision==0.8.2',
                      'pytorch-lightning==1.5.10',
                      'tensorboard==2.2.0',
                      'numpy==1.20.3',
                      'h5py==2.10.0',
                      'scipy==1.4.1',
                      'pillow==8.3.3',
                      'urllib3==1.26.11',
                      'numba==0.49.1',
                      'pooch==1.5.1',
                      'scikit-image==0.18.3',
                      'scikit-learn==0.24.2',
                      'face_recognition==1.3.0',
                      'face-alignment==1.3.4',
                      'facenet-pytorch==2.5.2',
                      'comet_ml'],
    entry_points = {
            'console_scripts': [
                'gasp_train=gazenet.bin.train:main',
                'gasp_infer=gazenet.bin.infer:main',
                'gasp_download_manager=gazenet.bin.download_manager:main',
                'gasp_scripts=gazenet.bin.scripts:main',
            ],
        },
    exclude_package_data={
        "datasets": ["*.zip", "*.7z", "*.tar.gz", "*.ptb", "*.ptb.tar", "*.npy", "*.npz", "*.hd5", "*.txt", "*.jpg", "*.png", "*.gif", "*.avi", "*.mp4", "*.wav", "*.mp3"]},
    package_data={
        "": ["datasets/processed/center_bias.jpg", "datasets/processed/center_bias_bw.jpg"],
    },
    data_files=[("datasets/processed/", ["datasets/processed/center_bias.jpg", "datasets/processed/center_bias_bw.jpg"])]
    )
